[package]
name = "webtoken"
edition = "2024"

[lib]
name = "_webtoken"
crate-type = ["cdylib"]

[dependencies]
aws-lc-rs = { version = "=1.15.4", features = ["unstable"] }   # ML-DSA-65 is currently supported on the unstable branch
blake2 = "0.10" 
graviola = "0.3.0"

base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_bytes = "0.11"

time = { version = "0.3", features = ["serde", "formatting", "parsing"] }

num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"

pythonize = "0.27"

[dependencies.pyo3]
version = "0.27" 
features = ["extension-module", "abi3-py311", "py-clone", "time"] 



[profile.release]
opt-level = 3       
lto = "fat"        
codegen-units = 1   
panic = "abort"     
strip = true        
