[package]
name = "webtoken"
edition = "2024"

[lib]
name = "_webtoken"
crate-type = ["cdylib"]

[dependencies]

# Main Crypto BE
aws-lc-rs = { version = "=1.17" }  

# Aux Crypto
graviola = "0.4"
blake2b_simd = "1.0.2"
chacha20 = "0.9"
argon2 = "0.5"
flate2 = "1.1"
subtle = "2.6"

base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_bytes = "0.11"

time = { version = "0.3", features = ["serde", "formatting", "parsing"] }

num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"


pythonize = "0.29"

[dependencies.pyo3]
version = "0.29" 
features = ["extension-module", "abi3-py312", "py-clone", "time"] 



[profile.release]
opt-level = 3       
lto = "fat"        
codegen-units = 1   
panic = "abort"     
strip = true        
