[build-system]
requires = ["maturin>=1.14"]
build-backend = "maturin"

[project]
name = "webtoken"
version = "0.6.0"
description = "A Rust-backed JWT library"
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/h5rdly/webtoken/wiki"

[tool.maturin]
features = ["pyo3/extension-module", "pyo3/abi3-py312"]
module-name = "webtoken._webtoken"

# Ignore "key too short" warnings when running tests
[tool.pytest.ini_options]
filterwarnings = [
    "ignore"
]
